name: Python bindings for RMVL

on:
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/rmvl-pybind.yml'
  workflow_call:

jobs:
  build_and_test:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4

    - name: Configure RMVL by CMake 
      run: cmake -B {{github.workspace}}/build -DBUILD_PYTHON=ON

    - name: Build RMVL
      run: cmake --build {{github.workspace}}/build --parallel 4
