name: GCC 14 support for RMVL 1.x and 2.x

on:
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/rmvl-u24.yml'
  workflow_call:

jobs:
  build_and_test:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt install -y libeigen3-dev libopencv-dev
        curl -SL https://github.com/microsoft/onnxruntime/releases/download/v1.18.1/onnxruntime-linux-x64-1.18.1.tgz -o onnxruntime-linux-x64-1.18.1.tgz
        tar -xf onnxruntime-linux-x64-1.18.1.tgz
        sudo mkdir /usr/local/include/onnxruntime
        cd onnxruntime-linux-x64-1.18.1
        sudo cp -r include/* /usr/local/include/onnxruntime
        sudo cp -r lib /usr/local

    - name: Configure RMVL by CMake 
      run: cmake -B {{github.workspace}}/build -DBUILD_EXTRA=ON -DBUILD_TESTS=ON -DBUILD_OPEN62541=ON -DCMAKE_C_COMPILER=/usr/bin/gcc-14 -DCMAKE_CXX_COMPILER=/usr/bin/g++-14

    - name: Build RMVL
      run: cmake --build {{github.workspace}}/build --parallel 4

    - name: Test RMVL
      run: ctest --test-dir {{github.workspace}}/build