name: Python bindings for RMVL 2.x

on:
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/rmvl-pybind-u22.yml'
  workflow_call:

jobs:
  build_and_test:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt install -y pybind11-dev

    - name: Configure RMVL by CMake 
      run: cmake -B {{github.workspace}}/build -DBUILD_PYTHON=ON -DBUILD_OPEN62541=ON

    - name: Build RMVL
      run: cmake --build {{github.workspace}}/build --parallel 4
