name: CMake install/uninstall support for RMVL 1.x and 2.x

on:
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/rmvl-install-u22.yml'
  workflow_call:

jobs:
  build_install_uninstall:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4

    - name: Configure RMVL by CMake 
      run: cmake -B {{github.workspace}}/build -DBUILD_EXTRA=OFF

    - name: Build RMVL
      run: cmake --build {{github.workspace}}/build --parallel 4

    - name: Install RMVL
      run: sudo cmake --install {{github.workspace}}/build
    
    - name: Uninstall RMVL
      run: sudo cmake --build {{github.workspace}}/build --target uninstall
