name: GCC 14 support for RMVL

on:
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/rmvl-u24.yml'
  workflow_call:

jobs:
  build_and_test:
    runs-on: ubuntu-22.04
    container:
      image: registry.cn-hangzhou.aliyuncs.com/cv-rmvl/rmvl-u24:latest
    steps:
    - uses: actions/checkout@v4

    - name: Configure RMVL by CMake 
      run: cmake -B {{github.workspace}}/build -DBUILD_EXTRA=ON -DBUILD_TESTS=ON

    - name: Build RMVL
      run: cmake --build {{github.workspace}}/build --parallel 4

    - name: Test RMVL
      run: |
        cd {{github.workspace}}/build
        ctest