name: CMake install/uninstall support for RMVL 1.x and 2.x

on:
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/rmvl-install-win.yml'
  workflow_call:

jobs:
  build_install_uninstall:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v4

    - name: Configure RMVL by CMake 
      run: cmake -B ${{ github.workspace }}/build -DBUILD_EXTRA=OFF

    - name: Build RMVL
      run: cmake --build ${{ github.workspace }}/build --parallel 4 --config Release

    - name: Install RMVL
      run: cmake --install ${{ github.workspace }}/build --config Release
    
    - name: Uninstall RMVL
      run: cmake --build ${{ github.workspace }}/build --target uninstall --config Release
