name: RMVL Ubuntu 20

on:
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/rmvl-u20.yml'
  workflow_call:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    container:
      image: registry.cn-hangzhou.aliyuncs.com/rm-vision/rmvl-docker:latest
    steps:
    - uses: actions/checkout@v3

    - name: Configure RMVL by CMake 
      run: cmake -B build -DBUILD_TESTS=ON

    - name: Build RMVL
      run: cmake --build build --parallel 8

    - name: Test RMVL
      run: |
        cd build
        ctest
